
version: 0.0
os: linux
files:
source: /
destination: /home/ec2-user/deploy
#permissions:
#object: /home/ec2-user/deploy
#pattern: "**"
#owner: ec2-user
#group: ec2-user
#mode: 644
#type:
hooks:
BeforeInstall:
- location: scripts/BeforeInstall.sh
timeout: 30
runas: root
AfterInstall:
- location: scripts/AfterInstall.sh
timeout: 120
runas: root
ApplicationStart:
- location: scripts/ApplicationStart.sh
timeout: 120
runas: root
ApplicationStop:
- location: scripts/ApplicationStop.sh
timeout: 30
