version: 0.0
os: linux
permissions:
  - object: /home/ec2-user/deploy
    pattern: "**"
    owner: ec2-user
    group: ec2-user
files:
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 3000
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 3600
      runas: ec2-user
