version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3600
