version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 3000
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 3000
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 3000
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 3000
