version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region ap-northeast-1)
    - URI=204065533127.dkr.ecr.ap-northeast-1.amazonaws.com
    - VER=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - TAG=${VER:=latest}
  build:
    commands:
    - echo Build started on date
    - echo Building the Docker image...
    - docker build -t $URI/jupyter:latest -f Chatbot_Line_cc103/dockerfile/dockerfile-jupyter2 Chatbot_Line_cc103/dockerfile/
    - docker build -t $URI/ngrok:latest -f Chatbot_Line_cc103/dockerfile/dockerfile-ngrok Chatbot_Line_cc103/dockerfile/
    - docker build -t $URI/api:latest -f Chatbot_Dev_cc103/dockerfile/dockerfile-api Chatbot_Dev_cc103/dockerfile/
    - docker tag $URI/jupyter:latest $URI/jupyter:$TAG
    - docker tag $URI/ngrok:latest $URI/ngrok:$TAG
    - docker tag $URI/api:latest $URI/api:$TAG  
  post_build:
    commands:
    - echo Build completed on date
    - echo Pushing the Docker image...
    - docker push $URI/jupyter:latest
    - docker push $URI/ngrok:latest
    - docker push $URI/api:latest
    - docker push $URI/jupyter:$TAG
    - docker push $URI/ngrok:$TAG
    - docker push $URI/api:$TAG
