version: '3'
services:
  db:
    image: mysql:latest 
    container_name: chatbot_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    volumes:
      - ./Chatbot_Dev_cc103/mysql_data:/var/lib/mysql
      - ./Chatbot_Dev_cc103/mysql_init:/docker-entrypoint-initdb.d/

  api:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/api:latest
    container_name: chatbot_api
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8880:8888"
 #     - "5001:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./Chatbot_Dev_cc103/code:/home/jovyan/work/
#    command: python /home/jovyan/work/code.py
    command: start-notebook.sh --NotebookApp.token=''

  redis:
    image: redis:latest
    container_name: chatbot_redis
    ports:
      - "6379:6379"
    volumes:
      - ./Chatbot_Line_cc103/redis/data:/data
      - ./Chatbot_Line_cc103/redis/redis.config:/usr/local/etc/redis/redis.conf
  jupyter-tutorial:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/jupyter:latest
    container_name: chatbot_line
    depends_on: 
      - api
      - redis
#      - ngrok-external-dns
    ports:
      - "8888:8888"
      - "80:5000"
    command: start-notebook.sh --NotebookApp.token=''
#    command: python /home/jovyan/work/test.py
    volumes:
      - ./Chatbot_Line_cc103/code:/home/jovyan/work

  ngrok-external-dns:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/ngrok:latest
    container_name: chatbot_ngrok
    depends_on: 
      - jupyter-tutorial
    ports:
      - "4040:4040"
    command: ngrok http chatbot_line:5000


